<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    
    <RootNamespace>DCT</RootNamespace>
    <AssemblyName>DCT</AssemblyName>
    
    <ApplicationIcon>Default.ico</ApplicationIcon>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
    
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>key.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

</Project>